### ISSUE TITLE
npm install before node server

### ISSUE THREAD

**Issue by nlebellier** [ricardotormo/beatpad-pi#3]
Just to say that we have to `npm install` before `node server` otherwise express.js is missing.
So the install instructions need to be changed :-)

**Comment by ricardotormo** [comment]
Thanks for pointing this out. I fixed the instructions!

**Comment by ricardotormo** [comment]
Could you elaborate on this: 

> Maybe put a different color on 1 5 9 13 column to help us to place the block.
I would like to understand what you mean and if is interesting, implementing it.

**Comment by nlebellier** [comment]
something like that : 
![chrome_RcwimqJFtZ](https://user-images.githubusercontent.com/4880966/81696374-1a790280-9464-11ea-85a4-274afa47420d.png)
https://codepen.io/nlb/pen/xxwzBJb

**Comment by ricardotormo** [comment]
Thanks for your answer, I added a slightly darker color to these positions.
